export const GET_WIN_NUMS_COMBOS_LOADING = 'GET_WIN_NUMS_COMBOS_LOADING'
export const GET_WIN_NUMS_COMBOS_SUCCESS = 'GET_WIN_NUMS_COMBOS_SUCCESS'
export const GET_WIN_NUMS_COMBOS_ERROR = 'GET_WIN_NUMS_COMBOS_ERROR'

export const CLEAR_SEARCH = 'CLEAR_SEARCH'
